# Problem 1 

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np



In [8]:
# 2 - 5 elemanlı bir numpy array oluşturun
x = np.array([9,8,7,4,5])
print(x)

[9 8 7 4 5]


In [11]:
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x = np.array([9,8,7,4,5])
print(x)
x.sort()
print(x)

[4 5 7 8 9]


# Problem 2

In [13]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
v = np.array([10,15,30,45,60])
print(v)

[10 15 30 45 60]


In [21]:
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
x = np.arange(5,15)
print(x)

[ 5  6  7  8  9 10 11 12 13 14]


In [23]:
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
x = np.arange(50,100,5)
print(x)

[50 55 60 65 70 75 80 85 90 95]


In [24]:
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
np.random.randint(10,30,5)

array([10, 15, 18, 26, 12])

In [43]:
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
np.random.randint(-1,1,10)                      

array([ 0, -1,  0,  0, -1,  0, -1,  0,  0, -1])

In [47]:
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
b= np.random.randint(10, 50, size = [3,5])
print(b)                                          

[[31 18 36 21 24]
 [34 27 32 27 37]
 [25 16 23 24 41]]


In [28]:
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ??????????????????????????????????????
b= np.random.randint(10, 50, size = [3,5])
satirTopla = b.sum(axis=1)
sutunTopla = b.sum(axis=0)
print("Satırların Toplamı")
print(satirTopla)
print("Sütünların Toplamı")
print(sutunTopla)


Satırların Toplamı
[151 151 135]
Sütünların Toplamı
[118  46 102  77  94]


In [29]:
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

buyuk = b.max()
print(buyuk)

kucuk = b.min()
print(kucuk)

ortalama= b.mean()
print(ortalama)

varyans = b.var()
print(varyans)



42
10
29.133333333333333
108.64888888888889


In [59]:
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?            ??????????SOR
b= np.random.randint(10, 50, size = [3,5])
buyuk = b.max()
print(buyuk)

49


In [64]:
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.   
import numpy as np
a = np.arange(10,20)
ucEleman = a[:3]
x = "soru 13:"
print(x) 
print(ucEleman)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
import numpy as np
a = np.arange(10,20)
tersi = a[::-1]
x= "soru 14:" 
print(x)
print(tersi)

# 15- Üretilen matrisin ilk satırını seçiniz.
import numpy as np
a = np.arange(10,20)
satir1 = a[0]
x = "soru 15:" 
print(x)
print(satir1)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir?

x ="soru 16:" 
print(x)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
eleman1 = b[:,0]
x= "soru 17:" 
print(x)
print(eleman1)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
square = np.power(b, 2)
x= "soru 18:" 
print(x)
print(square)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
x= "soru 19:" 
print(x)


soru 13:
[10 11 12]
soru 14:
[19 18 17 16 15 14 13 12 11 10]
soru 15:
10
soru 16:
soru 17:
[19 13 49]
soru 18:
[[ 361  961 1444 1296 1600]
 [ 169  400 2304  676  784]
 [2401  961  841  841  400]]
soru 19:
