# Problem 1

In [19]:
# 1 - numpy kütüphanesini import edin/
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin.
x = np.random.randint(0,10,5)
print(x)
# 3 - matris'in boyutunu öğrenin.
x = np.random.randint(0,10,5)
print(x.shape)

# 4 - matris'i yeniden boyutlandırın.
x = np.random.randint(0,10,5)
print(x.reshape(5,))

# 5 - matris'in boyut sayısını öğrenin
x = np.random.randint(0,10,5)
print(x.ndim)

[8 7 0 9 4]
(5,)
[3 1 7 9 7]
1


# Problem 2

In [31]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin.

import numpy as np
a = np.arange(1,10,2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın.

n = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np.split(n, [2,3]))

# 3 - Parçalanmış matrisleri birleştirin
x= np.array([1,2])
y= np.array([3])
z= np.array([4,5,6,7,8,9,10,11,12])
print(np.concatenate([x,y,z]))


[1 3 5 7 9]
[array([1, 2]), array([3]), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Problem 3

In [36]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin.

v = np.arange(5,100,2)
print(v)

# 2 - matris'in özelliklerini inceleyin.

print(v.ndim)
print(v.size)
print(v.dtype)
print(v.shape)


[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
1
48
int32
(48,)
