## Numpy
#### Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
#### Veri analizinde kullanılır.
#### Bilgisayarına kurmak için pip install numpy komutu ile kurulabilir.
#### Bilimsel hesaplamalar için kullanılır.
#### Arraylar/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
#### Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

## numpy kullanmak yerine klasik yöntem bu.

In [56]:
a = [1,2,3,4]                 
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]* b[i])
print(ab)

[2, 6, 12, 20]


## numpy kullanarak yapılan yöntem

In [57]:
import numpy as np              
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a*b)


[ 1  4  9 16]


.reshape ---> reshape fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.
.shape  ---> shape ile arraylerin boyutlarını öğrenebiliriz.
.ndim   ---> .ndim ile arraylerin boyut sayisini öğrenebiliriz.

In [58]:
x = np. array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)
print(multi.shape)
print(x.shape)
print(x.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(9,)
1


## Birleştirme: .concatenate() fonksiyonu ile birleşme yapabiliriz. 

In [59]:

x= np.array([1,2,3,4,5])
y= np.array([6,7,8,9,10])
print(np.concatenate([x,y]))


[ 1  2  3  4  5  6  7  8  9 10]


In [60]:

z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [61]:
a = np.array([[1,2,3], [4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


## axis=0 ise satır bazında birleştirme yapar.
## axis =1 ise sütün bazında birleştirme yapar.

In [62]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Array Ayırma(splitting)
### .split() fonksiyonu ile array ayırma yapabiliriz.

In [63]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m, [3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [64]:
a,b,c= np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


## vsplit() fonksiyonu ile array yatay olatak ayırma yapar.

In [65]:

n = np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## np.arange() belli aralıkta sayıları oluşturmak için kullanılır.
## np.arange(start,stop,step)

In [67]:

np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

## np.zeros() 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [68]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

## np.ones, 1'lerden oluşan bir numpy dizisidir.

In [69]:

np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## np.linspace(), belli bir aralıkta sayıları oluşturmak için kullanılır.
## np.linspace(başlangıç, bitiş, bölünecek aralık)

In [70]:

np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [71]:
np.random.randint(0,10,3)

array([0, 6, 2])

In [72]:
np.random.randint(2,22,5)

array([ 9, 10, 15,  2, 13])

In [73]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis=1))

[ 45 145 245 345 445]


## Numpy Array'in Özellikleri
#### ndim: boyut sayısı
#### shape: boyut bilgisi
#### siz: toplam eleman sayısı
#### dtype: veri tipi

In [137]:
a= np.random.randint(10, size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


1
(10,)
10
int32


##  Array Sıralama( sorting )
Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [75]:
v = np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [76]:
m = np.random.normal(20,5,(3,3))
print(m)

[[20.08909703 26.27321958 17.93232319]
 [19.30425789 10.51370855 20.87423892]
 [24.507636   18.60349709 20.70186485]]


In [77]:
print(np.sort(m, axis=0))

[[19.30425789 10.51370855 17.93232319]
 [20.08909703 18.60349709 20.70186485]
 [24.507636   26.27321958 20.87423892]]


In [78]:
print(np.sort(m,axis=1))

[[17.93232319 20.08909703 26.27321958]
 [10.51370855 19.30425789 20.87423892]
 [18.60349709 20.70186485 24.507636  ]]


## Index ile elemanlara erişmek

In [80]:
a = np.random.randint(10,size=10)
print(a[0])        #her seferinde farklı eleman getirecektir.

2


In [82]:
print(a[-1])   ##son elemanı getirmek için yaptık 

8


In [83]:
a[0] =100  ## a'nın ilk elemanını 100 alarak ekrana bastırır.
print(a) 

[100   6   7   8   9   9   4   5   6   8]


In [84]:
x = np.random.randint(10, size=[3,5])
print(x)

[[4 4 8 2 0]
 [6 9 9 5 0]
 [7 4 9 6 8]]


In [85]:
print(x[0,0])     #0. elemanın 0.indexini getir.

4


In [86]:
print(x[1,1])

9


In [87]:
x[1,4]=100
print(x)

[[  4   4   8   2   0]
 [  6   9   9   5 100]
 [  7   4   9   6   8]]


In [88]:
x[1,4] = 3.14
print(x)

[[4 4 8 2 0]
 [6 9 9 5 3]
 [7 4 9 6 8]]


## Slicing ile Elemanlarla Erişmek (Array Alt Kümesine Erişmek)

In [89]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [90]:
print(a[0:3]) #0-1-2 deki indexteki elemanları getir

[20 21 22]


In [91]:
print(a[:3])

[20 21 22]


In [93]:
print(a[3:])

[23 24 25 26 27 28 29]


In [94]:
print(a[1::2])
## 1 den başla ve 2 şer atla.

[21 23 25 27 29]


In [97]:
print(a[0::2])
#0-danbaşlka ikişer ikişer yazdır.

[20 22 24 26 28]


In [98]:
print(a[2::5])
#2-den başla 5er 5 er yazdır.

[22 27]


In [100]:
b= np.random.randint(10, size = [5,5])
print(b)

[[3 4 7 5 4]
 [7 3 7 5 4]
 [3 8 7 9 8]
 [4 0 4 5 6]
 [9 8 2 5 8]]


In [101]:
print(b[:,0]) 
# yukarıdaki kodda (,0)-ın anlamı: tüm satırlardaki sıfırncı sütündaki elemanları al

[3 7 3 4 9]


In [103]:
print(b[:,1])
#yukarıdaki kodda ise tüm satırşardaki 1. sütündaki elemanları ekrana bastırır.

[4 3 8 0 8]


In [104]:
print(b[0,:])
#0. sutündaki sayıları getirir.

[3 4 7 5 4]


In [105]:
print(b[0:2, 0:3])

[[3 4 7]
 [7 3 7]]


## Alt Küme Üzerinde İşlem Yapmak

In [108]:
alt_b = b[0:3,0:2]
alt_b

array([[3, 4],
       [7, 3],
       [3, 8]])

In [109]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b

array([[100,   4],
       [  7, 200],
       [  3,   8]])

## Fancy Index
### Bir liste içine bu arrayden istediğimiz indilerini koyarak o indislerdeli verileri alabiliriz.

In [110]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [111]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [116]:
m = np.arange(9).reshape(3,3)
print(m)
print("---------------")
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir,sutun])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
[1 5]


## Koşullu Eleman İşlemleri

In [118]:
v = np.array([1,2,3,4,5])
print(v>3)
# 3 ten büyükleri döndürdü.

[False False False  True  True]


In [119]:
print(v[v>3])

## kod açıklaması: 3 ten büyük olanları bul getir.
# ve bunu v deki indexlerine yerleştitir. 3ten büyükleri beana getir.

[4 5]


In [123]:
print(v[v>=3])
print("--------")
print(v[v<=3])
print("--------")
print(v[v!=3])
print("--------")
print(v[v==3])

[3 4 5]
--------
[1 2 3]
--------
[1 2 4 5]
--------
[3]


## Matematiksel İşlemler

In [124]:
v = np.array([1,2,3,4,5])
print(v*2)
#sırayla ikiyle çarptı.

[ 2  4  6  8 10]


In [132]:
print(v+2)
print(v*5/10)
print(v**2)

print("-----------")

print(np.subtract(v,3)) # her birinden 3 sayısını çıkartır.

print("-----------")

print(np.add(v,2))      # ekleme işlemi yapar.

print("-----------")

print(np.multiply(v,2))   # çarpma

print("-----------")

print(np.divide(v,2)) # bölme

print("-----------")

print(np.power(v,2))      # üs alma

print("-----------")

np.mod(v,5)               #mod alma işlemi yapar

print("-----------")

print(np.absolute(v))      #mutlak değer

print("-----------")

print(np.sin(360))       # sinüs alır.

print("-----------")

print(np.log(10))        # logaritma işlemi


[3 4 5 6 7]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
-----------
[-2 -1  0  1  2]
-----------
[3 4 5 6 7]
-----------
[ 2  4  6  8 10]
-----------
[0.5 1.  1.5 2.  2.5]
-----------
[ 1  4  9 16 25]
-----------
-----------
[1 2 3 4 5]
-----------
0.9589157234143065
-----------
2.302585092994046


## İki bilinmeyenli denklem çözümü

### 5*x0 + x1 = 12
### x0 + 3*x1 = 10


#### linalg 2 bilinmeyenli denklem çözümünde kullanılan fonksiyondur.

In [136]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b) 
print(x)

[1.85714286 2.71428571]


array ve normal array farkı
np daha performanslı 
ramden farklı yerden seçiyor 
numpy daha farklı
numpydaki arrayde sadece bir int girilir.
np daha hızlı